### PR TITLE
initial commit for adding korok seeds

### PR DESCRIPTION
**Pull request by run-time**
added 12 different catergories for the different types of korok seeds
and added locations for the korok seeds on great plateau

### CODE REVIEW

**Comment by willmanduffy** [comment]
This is awesome! Thanks. I'm going to merge this in and then refactor a few things to keep the architecture generic for some future changes I have in mind :D This was a huge help!

**Comment by willmanduffy** [comment]
This is now on production! https://www.hyrule.site

You can find the small refactor here: https://github.com/willmanduffy/breath-of-the-wild-map/commit/0abef54327d3ec901d26f4c9d993f8aabe2b935e I mostly just wanted to keep the idea of "instructions" as a generic because I am thinking forward to a future where I use this for code for other open world game maps! :)

**Comment by willmanduffy** [comment]
(Final update, if you're interested in doing any more I've outlined a system to break this apart here)

https://github.com/willmanduffy/breath-of-the-wild-map/milestone/1

**Comment by run-time** [comment]
cool.  I'm working on the locations for seeds around other towers

**Pull request merged**
