### PR TITLE
Memory locations

### PR DESCRIPTION
**Pull request by toddself**
Couldn't find a good icon...

And this isn't all of them.  Will update with the rest soon :)

### CODE REVIEW

**Comment by toddself** [comment]
Just missing three of the memories.  Back to the game!

**Comment by toddself** [comment]
This has all but the very last one which is going to take some getting since it's in the castle.

**Comment by toddself** [comment]
@willmanduffy this is complete now thanks to your last tip :)

**Comment by willmanduffy** [comment]
o hell ya let's do this

**Pull request merged**
